### ISSUE TITLE
testing the task list and issues with lost data

### ISSUE THREAD

**Issue by matthiku** [matthiku/myOwnApi#1]
- [x] task 1 from chrome on computer 1

- [x] task 2 from computer 1

- [x] task 3 from computer 2

- [x] task 4 from computer 2

asdfasdf asdf
